### ISSUE TITLE
Inference results seems incorrect

### ISSUE THREAD

**Issue by eshafeeqe** [MM4SPA/tvcalib#3]
Hi, 

Thanks for open sourcing the repository. I tried the inference script and produced results as shown below. I think it seems incorrect and have some scaling issue when generating the result images. 

![1](https://user-images.githubusercontent.com/5008123/227828711-ab35a249-ff10-451c-9b24-3091e5d9a8ca.png)
![107](https://user-images.githubusercontent.com/5008123/227828753-ef1b43c2-f9e8-41b7-a69e-f4e2d95ccb98.png)
![162](https://user-images.githubusercontent.com/5008123/227828766-52ee6e46-a81e-4c2e-bf49-9f7c394eb39a.png)

**Comment by eshafeeqe** [comment]
Fixed the issue, the image size was wrong.

**Comment by jtheiner** [comment]
Thanks for the hint. Updated the example.
