### ISSUE TITLE
Camera Calibration -> Homography

### ISSUE THREAD

**Issue by donalSE** [MM4SPA/tvcalib#5]
Hi, 
Just wondering how does one got from the Outpict Dict of the camera calibration to a Homography Matrix?

Or more generally, given the camera has been calibrated, how do I localise players on the field? It's not so clear cut from the inference scripts.

Thanks

**Comment by jtheiner** [comment]
Hi,
from the camera parameter dict, the projective matrix is constructed via https://github.com/MM4SPA/tvcalib/blob/main/tvcalib/inference.py#L48

The homography is then calculated from the projective matrix (according to Z=0). See https://github.com/MM4SPA/tvcalib/blob/main/tvcalib/cam_modules.py#L433

> ... the camera has been calibrated, how do I localise players on the field? It's not so clear cut from the inference scripts.

Player localization and projection to the top view (world) are not part of this repo. You have to use the inverse homography matrix to project arbitrary pixels to the top view.

Hope that helps :)

**Comment by donalSE** [comment]
Many thanks for your response.

Is the projective camera only useful for samples that the model has been trained on so?

If I was to call this inside a frame loop of a video, how would the projective camera fair in obtaining a homography matrix for every other frame?

**Comment by jtheiner** [comment]
> Is the projective camera only useful for samples that the model has been trained on so?

The projective camera is independent of the segmentation model. It only defines the projection from the 3D world to 2D image, while the homography describes the mapping between 2D world and 2D image. 

> If I was to call this inside a frame loop of a video, how would the projective camera fair in obtaining a homography matrix for every other frame?

I don't know exactly what you mean. The camera parameters change from frame to frame, hence the resulting projective matrix and homography matrix also differ slightly.
