### ISSUE TITLE
Mapping pixel coordinates to top view

### ISSUE THREAD

**Issue by matleys** [MM4SPA/tvcalib#6]
Hi,
Thanks a lot for this repo - very useful.
I was just wondering what the code would look like to project an arbitrary pair of pixel coordinates to their real-world counterpart (e.g., some distance in meters).

I tried the following code snippet without but the results were plainly incorrect:
```
# Assume we want to know where pixel (10, 20) in the original image would map to in the real world
x = np.array([10])
y = np.array([20])

xy = np.vstack([x, y, np.full_like(x, 1.)])

h = df.iloc[0]['homography']
unscaled_x, unscaled_y, scale = h @ xy
proj_x, proj_y = unscaled_x/scale, unscaled_y/scale
# If my interpretation (& maths) are correct this should be the answer but it is not correct
```

Am I missing something? What coordinate system does this homography matrix map pixel coordinates in the original image to?
Thanks!

**Comment by jtheiner** [comment]
Hi, 
basically, you are right and it's the coordinate system.
The underlying coordinate system of the projection matrix $P$ is based on the [SoccerNet calibration repository](https://github.com/SoccerNet/sn-calibration):
<img src="https://github.com/SoccerNet/sn-calibration/blob/main/doc/axis-system-resized.jpeg?raw=true"  width="50%" height="50%">

You have to translate the provided homography matrix $H$ (and optionally scale for visualization purposes) first according to $S T H$ where 

$$T= \left[\begin{matrix} 1 & 0 & 105/2 \\\ 0 & 1 & 68/2 \\\ 0 & 0 & 1 \end{matrix}\right] $$

and $S$ is a scaling matrix.

![wc14_0](https://github.com/MM4SPA/tvcalib/assets/24683838/666a4c08-ea17-41cb-a135-6234575b03f7)

See [pixel2world_homography_example.ipynb](https://github.com/MM4SPA/tvcalib/blob/main/pixel2world_homography_example.ipynb)
